# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./incl/stdafx.h \
	./incl/targetver.h

SOURCES += ./srce/CTCFibonacci.cpp \
	./srce/stdafx.cpp

